config/routes.rb
Rails.application.routes.draw do





  root 'static_pages#home'

  get     '/home',            to: 'static_pages#home'
  get     '/instrucciones',   to: 'static_pages#instrucciones'
  get     '/resultados',      to: 'static_pages#resultados'
  get     '/contacto',        to: 'static_pages#contacto'
  get     '/login',           to: 'sessions#new'
  post    '/login',           to: 'sessions#create'
  delete  '/logout',          to: 'sessions#destroy'
  get     '/stats',           to: 'stats#create'  #personalizada



  resources :stats, only: [:create, :show] do
    resources :stat_steps, only: [:edit, :update]
  end

  #lo de arriba permite=>  stats/:stat_id/stat_parts/:id/edit

  resources :stats

  resources :places do
    resources :commons, :users
  end

  resources :users #hay disonancia de que esta línea tenga que existir

  resources :commons #no deja de ser necesaria la declaración de estas rutas.
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/models/common.rb
class Common < ApplicationRecord
  has_many :shares
  has_many :users, through: :shares
  belongs_to :place
  has_many :transactions
  has_many :outcomes, through: :transactions
end

app/controllers/commons_controller.rb
class CommonsController < ApplicationController
  before_action :set_common, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:new, :index, :edit, :update, :show, :destroy]

  # GET /commons
  # GET /commons.json
  def index
    @commons = Common.paginate(page: params[:page])
  end

  # GET /commons/1
  # GET /commons/1.json
  def show
    @common = Common.find(params[:id])
  end

  # GET /commons/new
  def new
    @place = Place.find(params[:place_id])
    @common = Common.new
  end

  # GET /commons/1/edit
  def edit
  end

  # POST /commons
  # POST /commons.json
  def create
    @place = Place.find(params[:place_id])
    @common = @place.commons.build(common_params) #updated because Place asociation
    #Se observa que aquí [ »·« ] opera 'resources: commons'
    #sin este chunk no existirían rutas que proporcionar para '/common'
    respond_to do |format|
      if @common.save
        format.html { redirect_to @common, notice: 'Common was successfully created.' }
        format.json { render :show, status: :created, location: @common }
      else
        format.html { render :new }
        format.json { render json: @common.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commons/1
  # PATCH/PUT /commons/1.json
  def update
    respond_to do |format|
      if @common.update(common_params)
        format.html { redirect_to @common, notice: 'Common was successfully updated.' }
        format.json { render :show, status: :ok, location: @common }
      else
        format.html { render :edit }
        format.json { render json: @common.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commons/1
  # DELETE /commons/1.json
  def destroy
    @common.destroy
    respond_to do |format|
      format.html { redirect_to commons_url, notice: 'Common was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_common
      @common = Common.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def common_params
      params.require(:common).permit(:plus, :balance, :place_id)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/commons_helper.rb
module CommonsHelper
end

app/views/commons/_form.html.erb
<%= form_for([place, common]) do |f| %>
  <% if common.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(common.errors.count, "error") %> prohibited this common from being saved:</h2>

      <ul>
      <% common.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for([place, common]) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :acumulado %>
        <%= f.text_field :plus, class: 'form-control' %>

        <%= f.label :saldo %>
        <%= f.text_field :balance, class: 'form-control' %>

        <%= f.submit "Iniciar juego", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/commons/edit.html.erb
<h1>Editing Common</h1>

<%= render 'form', common: @common %>

<%= link_to 'Show', @common %> |
<%= link_to 'Back', commons_path %>

app/views/commons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Commons</h1>

<table>

  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commons.each do |common| %>

<!--     <% "hola "%>
    <%puts common.place_id%> -->
      <tr>
        <td><%= link_to 'Show', place_common_path(common) %></td>
        <td><%= link_to 'Edit', edit_place_common_path(common) %></td>
        <td><%= link_to 'Destroy', common, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br>

<%= link_to 'New Common', new_place_common_path %>

app/views/commons/new.html.erb
<% provide(:title, 'Ronda') %>
<h1>inicializar ronda</h1>

<%= render 'form', place: @place, common: @common %>

<%= link_to 'Back', :back %>

app/views/commons/show.html.erb
<% provide(:title, @common.plus) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @common.plus.to_s + " " + @common.balance.to_s %>
      </h1>
    </section>
  </aside>
</div>