config/routes.rb
Rails.application.routes.draw do





  root 'static_pages#home'

  get     '/home',            to: 'static_pages#home'
  get     '/instrucciones',   to: 'static_pages#instrucciones'
  get     '/resultados',      to: 'static_pages#resultados'
  get     '/contacto',        to: 'static_pages#contacto'
  get     '/login',           to: 'sessions#new'
  post    '/login',           to: 'sessions#create'
  delete  '/logout',          to: 'sessions#destroy'
  get     '/stats',           to: 'stats#create'  #personalizada



  resources :stats, only: [:create, :show] do
    resources :stat_steps, only: [:edit, :update]
  end

  #lo de arriba permite=>  stats/:stat_id/stat_parts/:id/edit

  resources :stats

  resources :places do
    resources :commons, :users
  end

  resources :users #hay disonancia de que esta línea tenga que existir

  resources :commons #no deja de ser necesaria la declaración de estas rutas.
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/models/place.rb
class Place < ApplicationRecord
  has_many :users
  has_many :commons
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:new, :index, :edit, :update, :show, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.paginate(page: params[:page])
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place   =  Place.find(params[:id])
    @users   =  @place.users.paginate(page: params[:page]) #conseguimos una vista de los users asociados a Place
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :age, :population) # »»» indica los params Padre_santo «««
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<% provide(:title, 'Agregar Habitats') %>
<h1>Registrar Hábitats</h1>

<%= form_for(place) do |f| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@place) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :Nombre %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :Antiguedad %>
      <%= f.text_field :age, class: 'form-control' %>

      <%= f.label :Cantidad_de_departamentos %>
      <%= f.text_field :population, class: 'form-control' %>

      <%= f.submit "Agregar hábitat", class: "btn btn-primary" %>
    <% end %>

  </div>

</div>
<% end %>

app/views/places/_place.html.erb
<li>

  <%= link_to place.name, place %> <!--otra corrección sutil e indispensable de la ruta-->

  <% if current_user.admin? && !current_user?(user) %>
  | <%= link_to "edit",  edit_place_path(place.id) %>
  | <%= link_to "delete", place, method: :delete, data: { confirm: "¿Seguro, carnal?" } %>

  <% end %>

</li>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<% provide(:title, 'Hábitats') %>
<h1>Hábitats</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @places, user: @user %> <!--corrección sutil e indispensable para operar el código de _place-->
    <br>
    <%= link_to "Agregar", new_place_path, class: "btn btn-primary" %>
</ul>


<%= will_paginate %>











<!-- <p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %> -->

app/views/places/new.html.erb
<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<% provide(:title, @place.name) %>
<p id="notice"><%= notice %></p>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @place.name %>
        <%= "   " %>
        <%= @place.age %>
        <%= "   " %>
        <%= @place.population %>
      </h1>
    </section>
  </aside>
</div>

<div class="col-md-8">    <!--agrgado para mejorar-->
   <% if @place.users.any? %>
     <h3>Users (<%= @place.users.count %>)</h3>
     <ol class="microposts">
       <%= render @users %>
     </ol>
     <%= will_paginate @users %>
   <% end %>
 </div>


<%= link_to "Agregar usuarios", new_place_user_path(@place), class: "btn btn-primary" %>

<%= link_to "iniciar ronda", new_place_common_path(@place), class: "btn btn-primary" %>