config/routes.rb
Rails.application.routes.draw do





  root 'static_pages#home'

  get     '/home',            to: 'static_pages#home'
  get     '/instrucciones',   to: 'static_pages#instrucciones'
  get     '/resultados',      to: 'static_pages#resultados'
  get     '/contacto',        to: 'static_pages#contacto'
  get     '/login',           to: 'sessions#new'
  post    '/login',           to: 'sessions#create'
  delete  '/logout',          to: 'sessions#destroy'
  get     '/stats',           to: 'stats#create'  #personalizada



  resources :stats, only: [:create, :show] do
    resources :stat_steps, only: [:edit, :update]
  end

  #lo de arriba permite=>  stats/:stat_id/stat_parts/:id/edit

  resources :stats

  resources :places do
    resources :commons, :users
  end

  resources :users #hay disonancia de que esta línea tenga que existir

  resources :commons #no deja de ser necesaria la declaración de estas rutas.
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Universidad Nacional Autonoma de México. Investigación: 105678-fs
  </small>
  <nav>
    <ul>
      <li><a href="https://www.unam.mx">UNAM</a></li>
      <li><%= link_to "Contact", contacto_path %></li>
      <li><a href="http://www.instructables.com">Un link</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "COOPER", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><%= link_to "Home", root_path %></li> -->
        <!-- <li><%= link_to "Ingresar", login_path %></li> -->


<!-- refactorizar lo de abajo -->

        <% if logged_in? && current_user.admin? %>
        <li><%= link_to "Instrucciones", '#' %></li>
        <li><%= link_to "Resultados", '#' %></li>
        <!-- <li><%= link_to "Participantes", users_path %></li>  hemos de anidar esta ruta en Lugares-->
        <li><%= link_to "Lugares", places_path%></li>
        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= depto_user %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
              <li><%= link_to "Cuenta personal", current_user %></li>
              <li><%= link_to "Cuenta pública", '#' %></li>

              <li class="divider"></li>
              <li><%= link_to "Salir", logout_path, method: "delete" %></li>
          </ul>
        </li>
        <% elsif logged_in? && !current_user.admin? %>
        <li><%= link_to "Instrucciones", '#' %></li>
        <li><%= link_to "Resultados", '#' %></li>
        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= depto_user %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
              <li><%= link_to "Cuenta personal", current_user %></li>
              <li><%= link_to "Cuenta pública", '#' %></li>

              <li class="divider"></li>
              <li><%= link_to "Salir", logout_path, method: "delete" %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Ingresar", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>


<!-- <li><%= link_to "Instrucciones", '#' %></li> -->
<!-- <li><%= link_to "Resultados" %></li> -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>